# Generated by Django 2.2 on 2019-04-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190410_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='profile',
        ),
    ]
